import styles from "../../styles/Favorites.module.scss";
import { useSession, signIn } from "next-auth/react";
import { useState, useEffect } from "react";
import Head from "next/head";
import MenuDesk from "@/components/menuDesk";
import MenuMobile from "@/components/menuMobile";
import Footer from "@/components/footer";
import CardList from "@/components/cardList";

export default function Favorites() {
  const { data: session, status } = useSession({
    required: true,
    onUnauthenticated() {
      signIn();
    },
  });

  const [favorites, setFavorites] = useState([]);

  useEffect(() => {
    if (session) {
      const favorites = JSON.parse(localStorage.getItem("favorites")) || [];
      setFavorites(favorites);
    }
  }, [session]);

  return (
    <div className={styles.Favorites}>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navFavorites}>
        <MenuDesk />
        <MenuMobile />

        <div className={styles.textNav}>
          <h1>
            Welcome to your collection of favorite experiences! Here you can
            keep track of all the adventures you've loved the most with us. Add
            the experiences you want to relive over and over again. Each
            experience is a precious piece in your journey of discovery. Keep
            exploring and creating unforgettable memories with us!
          </h1>
        </div>
      </nav>
      <main className={styles.mainFavorites}>
        {favorites.length === 0 ? (
          <h3 className={styles.noFavorites}>
            You have no favorite experiences yet.
          </h3>
        ) : (
          <CardList experiences={favorites} />
        )}
      </main>
      <Footer />
    </div>
  );
}
