import styles from "../../styles/AboutUs.module.scss";
import Head from "next/head";
import MenuDesk from "@/components/menuDesk";
import MenuMobile from "@/components/menuMobile";
import Footer from "@/components/footer";

export default function AboutUs() {
  return (
    <div className={styles.AboutUs}>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.navAboutUs}>
        <header>
          <MenuDesk />
          <MenuMobile />
        </header>
      </nav>
      <main className={styles.main}>
        <div className={styles.textOne}>
          <h1>About Us</h1>
          <p>Welcome to Sicily Experience App!</p>
          <p>
            At Sicily Experience, we are passionate about showcasing the beauty,
            culture, and traditions of Sicily. Our goal is to provide users with
            unforgettable experiences that allow them to immerse themselves in
            the rich history and vibrant atmosphere of this magnificent island.
          </p>
          <h2>Our Team</h2>
          <p>
            Meet the dedicated rockstars who work on the Sicily Experience App:
          </p>
          <ul>
            <li>
              <a href="https://www.linkedin.com/in/federica-iuvara">
                Federica Iuvara
              </a>
              - Software Developer
            </li>
            <li>
              <a href="https://www.linkedin.com/in/paolo-spoto-894110227/">
                Paolo Spoto
              </a>
              - Software Developer
            </li>
            <li>
              <a href="https://www.linkedin.com/in/rita-teresa-landino-a7a54b2b4/">
                Rita Landino
              </a>
              - Software Developer
            </li>
            <li>
              <a href="https://www.linkedin.com/in/alessio-restivo/">
                Alessio Restivo
              </a>
              - Software Developer
            </li>
            <li>
              <a href="https://www.linkedin.com/in/elia-di-lorenzo-526040235/">
                Elia Di Lorenzo
              </a>
              - Software Developer
            </li>
          </ul>
        </div>
        <div className={styles.textTwo}>
          <h2>Our Values</h2>
          <ul>
            <li>
              <span className={styles.values}>Authenticity</span> : We strive to
              offer authentic experiences that truly capture the essence of
              Sicily.
            </li>
            <li>
              <span className={styles.values}> Community</span>: We believe in
              fostering a sense of community among our users, connecting them
              with locals and fellow travelers alike.
            </li>
            <li>
              <span className={styles.values}>Quality</span>: We are committed
              to delivering high-quality experiences that exceed our users'
              expectations.
            </li>
            <li>
              <span className={styles.values}>Inclusivity</span>: We welcome
              everyone to explore Sicily with us, regardless of background or
              experience. Our hosts are fluent in English and highly trained to
              offer services to both locals and tourists.
            </li>
          </ul>
          <h2>Contact Information</h2>
          <p>
            If you have any questions or inquiries, please don't hesitate to
            contact us:
          </p>
          <p className={styles.values}>
            Email: customerservice@sicilyexperience.com
          </p>
          <p className={styles.values}>
            Address: Via Roma, 123 - Palermo, Sicily
          </p>
          <p className={styles.values}>Phone: +39 123 456 789</p>
        </div>
      </main>

      <Footer />
    </div>
  );
}
