import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <div>
          <img src="/logoipsum-331.svg" alt="logo" />
        </div>
        <div>
          <input type="text" placeholder="Search..." />
        </div>
        <div>
          <button>Food & wine</button>
          <button>Wellness</button>
          <button>Events</button>
          <button>Open Air</button>
        </div>
      </nav>
      <main></main>
    </>
  );
}
