import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <div>
          <img src="/logoipsum-331.svg" alt="logo" />
        </div>
        <div>
          <input type="text" placeholder="Search..." />
        </div>
        <div>
          <button>Food & wine</button>
          <button>Wellness</button>
          <button>Events</button>
          <button>Open Air</button>
        </div>
      </nav>
      <main>
        {/* //h2 Title */}
        <div>
          <h2>#Experience for you</h2>
          <Link href="#">See all</Link>
        </div>

        {/* //Slider */}
        <div>
          <div>
            <h4>Titolo Evento</h4>
            <p>Orario</p>
            <p>Città</p>
          </div>
        </div>

        {/* //h2 Title */}
        <div>
          <h2>#Show Experience</h2>
        </div>

        {/* List with random cards, but updates when the search is performed */}
        <section>
          <div>
            <div>
              <span>Heart Icon</span>
              <span>Rating stars</span>
            </div>
            <div>
              <h4>Titolo Evento</h4>
              <p>Orario</p>
              <p>Città</p>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
