import styles from "../../styles/Home.module.scss";
import Head from "next/head";
import Link from "next/link";

import { IconHome } from "@tabler/icons-react";
import { IconHeart } from "@tabler/icons-react";
import { IconStar } from "@tabler/icons-react";
import { IconSailboat } from "@tabler/icons-react";
import { IconUserCircle } from "@tabler/icons-react";
import ImageSlider from "@/components/imageSlider";
import MenuMobile from "@/components/menuMobile";
import Card from "@/components/card";

// Immagini dello slider
const images = ["/exp1.jpg", "/sicilyexp-pic.jpeg"];

export default function Home() {
  return (
    <div className={styles.Home}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ---NAV--- */}
      <nav className={styles.navPageHome}>
        <div className={styles.containerDesk}>
          <div className={styles.containerImage}>
            <img src="/logoipsum-331.svg" alt="logo" />
          </div>
          <div className={styles.topMenu}>
            <Link href="/#">Preferiti</Link>
            <Link href="/#">Esperienze</Link>
            <Link href="/#">Profilo</Link>
            <Link href="/#">Contatti</Link>
            <Link href="/#">About Us</Link>
          </div>
        </div>
        <div>
          <div className={styles.containerInput}>
            <input type="text" placeholder="search..." />
            <button>Click</button>
          </div>
          <div className={styles.filterIcons}>
            <button>Food & wine</button>
            <button>Wellness</button>
            <button>Events</button>
            <button>Open Air</button>
          </div>
        </div>
      </nav>
      {/* ---MAIN--- */}
      <main className={styles.mainPageHome}>
        <div className={styles.textDesk}>
          <h1>Uncover Sicily with SicilyExperience!</h1>
          <p>
            Embark on a captivating journey through the heart of Sicily with
            SicilyExperience. Our platform offers more than just a booking
            experience - it's your ultimate guide to exploring Sicily, tailored
            to your interests and preferences.
          </p>
        </div>
        <div className={styles.titleAndLink}>
          <h2>#Experience for you</h2>
          <Link href="#">See all</Link>
        </div>

        {/* //Slider */}
        <ImageSlider images={images} />
        <div className={styles.containerSlider}>
          <div className={styles.boxSlider}>
            <h4>Titolo Evento</h4>
            <p>Orario</p>
            <p>Città</p>
          </div>
          {/* <div className={styles.boxSlider}>
            <h4>Titolo Evento</h4>
            <p>Orario</p>
            <p>Città</p>
          </div>
          <div className={styles.boxSlider}>
            <h4>Titolo Evento</h4>
            <p>Orario</p>
            <p>Città</p>
          </div>
          <div className={styles.boxSlider}>
            <h4>Titolo Evento</h4>
            <p>Orario</p>
            <p>Città</p>
          </div> */}
        </div>

        <div className={styles.titleAndLink}>
          <h2>#Show Experience</h2>
        </div>

        {/* List with random cards, but updates when the search is performed */}
        <Card />
      </main>
      {/* bottom menu */}
      {/* ---HEADER-- */}
      <header>
        <MenuMobile />
      </header>
      {/* ---FOOTER--- */}
      <footer className={styles.footer}>
        <p>Copyright</p>
      </footer>
    </div>
  );
}
