import styles from ".././styles/Intro.module.scss";
import { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useSession, signIn, signOut } from "next-auth/react";
import router from "next/router";
import SignUpForm from "@/components/signUpForm";
import SignInButton from "@/components/signInButton";

export default function Intro() {
  const { data: session } = useSession();
  const [isFormVisible, setIsFormVisible] = useState(false);
  const [isShowPage, setIsShowPage] = useState(true);

  useEffect(() => {
    console.log(session);
  }, [session]);

  if (session?.user.username) {
    router.push("/home");
  }

  if (session?.user.username) {
    return null;
  }

  const handleRegistration = (state) => {
    setIsFormVisible(state);
    setIsShowPage(!state);
  };

  return (
    <div className={styles.Intro}>
      <Head>
        <title>Sicily Experience</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isFormVisible && <SignUpForm isClose={handleRegistration} />}
        {isShowPage && (
          <>
            <div className={styles.logo}>
              <Image
                src="/logoBianco.svg"
                width={100}
                height={100}
                className={styles.logoImage}
                alt="logo"
                priority
              />
            </div>

            <h1>Find interest experience to Join in Sicily!</h1>
            <p>We share all experiences!</p>

            <SignInButton />

            <Link href="/home">Browse as guest</Link>
          </>
        )}
      </main>
    </div>
  );
}
